In [1]:
import pandas as pd
import numpy as np
import scipy

In [2]:
#url = 'http://island.ricerca.di.unimi.it/~alfio/shared/worldcities.xlsx'
df= pd.read_excel(r"C:\Users\cibei\OneDrive\Desktop\Coding_for_data_science\Python\dscoding-projects\niccolo.cibei\project\dataset\worldcities.xlsx")

In [1]:
import pandas as pd
from shapely.geometry import Point
import geopandas as gpd
from geopandas import GeoDataFrame


geometry = [Point(xy) for xy in zip(df['lng'], df['lat'])]
gdf = GeoDataFrame(df, geometry=geometry)   

#this is a simple map that goes with geopandas
world = gpd.read_file(gpd.datasets.get_path('naturalearth_lowres'))
gdf.plot(ax=world.plot(figsize=(10, 6)), marker='o', color='red', markersize=15);

ModuleNotFoundError: No module named 'shapely'

In [ ]:
import plotly.graph_objects as go

def plot_shortest_path(df, shortest_path):
    # Estrai le coordinate delle città
    city_coords = df[['lat', 'lng']].to_numpy()

    # Estrai le coordinate del percorso
    path_coords = [city_coords[city_id - 1] for city_id in shortest_path]

    # Crea un grafico a dispersione con il percorso
    fig = go.Figure()

    fig.add_trace(go.Scattergeo(
        locationmode="ISO-3",
        lon=[coord[1] for coord in city_coords],
        lat=[coord[0] for coord in city_coords],
        mode="markers",
        marker=dict(size=8, color="red"),
        hoverinfo="text",
        text=df['city_ascii'],
        name="Cities"
    ))

    fig.add_trace(go.Scattergeo(
        locationmode="ISO-3",
        lon=[coord[1] for coord in path_coords],
        lat=[coord[0] for coord in path_coords],
        mode="lines+markers",
        line=dict(width=2, color="blue"),
        marker=dict(size=8, color="blue"),
        hoverinfo="text",
        text=df['city_ascii'][shortest_path],
        name="Shortest Path"
    ))

    fig.update_geos(projection_type="natural earth", showland=True, landcolor="rgb(250, 250, 250)")

    fig.show()


In [5]:
a = np.arange(100)
a.mean()

49.5

In [11]:
a = np.random.normal(size= (10,2))

a.min(axis= 0)
a.max(axis= 0)

array([2.04577974, 1.88053823])

In [22]:
a = np.random.normal(size= (10,2), loc= 5)
a.mean(axis= 0)

array([[3.92554448, 4.38277689],
       [3.49899313, 5.8935898 ],
       [5.73954567, 3.57643504],
       [3.88927224, 5.08858007],
       [3.64576946, 5.05827069],
       [5.48008484, 5.38699051],
       [6.21046817, 4.97987046],
       [5.01039395, 4.16716205],
       [4.88398942, 4.29837233],
       [3.61060658, 5.49059556]])

In [27]:
np.random.seed(2)
a = np.random.randint(low= 1, high= 10, size = (5,2))

np.nonzero(a == a.max())

(array([0, 0, 2], dtype=int64), array([0, 1, 0], dtype=int64))

In [28]:
np.sum (a == a.max())

3

In [30]:
np.sum (a > a.mean())

5

In [31]:
a =np.random.random(size = (3,2))
(a- a.mean())/a.std()

array([[ 0.69042756,  0.29288513],
       [-1.4122158 ,  0.22562539],
       [-1.19674608,  1.4000238 ]])

In [32]:
a =np.random.random(size = (3,2))
(a- a.mean(axis=0))/a.std(axis=0)

array([[ 0.7297718 ,  1.4135993 ],
       [ 0.68419696, -0.6707057 ],
       [-1.41396876, -0.7428936 ]])

In [37]:
a = np.arange(60).reshape(6, -1)[:, :6]

In [42]:
a[[0, 0, 2, 4], [1, 5, 3, 2]]

array([[11, 12, 13, 14],
       [31, 32, 33, 34],
       [51, 52, 53, 54]])

In [ ]:
a[[1, 3, 5],  1:5]


In [50]:
#a[1:, [0,5]]

a[(a % 5 == 0 )& (a > 5)]

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55])