In [1]:
import pandas as pd
import openpyxl


In [2]:
guests_table= pd.read_excel(r"C:\Users\lejda\Desktop\coding - Python\guests.xlsx")
guests_table

Unnamed: 0       guest  discount
0              0     guest_1      0.09
1              1     guest_2      0.00
2              2     guest_3      0.07
3              3     guest_4      0.00
4              4     guest_5      0.10
...          ...         ...       ...
3995        3995  guest_3996      0.00
3996        3996  guest_3997      0.15
3997        3997  guest_3998      0.07
3998        3998  guest_3999      0.08
3999        3999  guest_4000      0.07

[4000 rows x 3 columns]

In [3]:
hotels_table = pd.read_excel(r"C:\Users\lejda\Desktop\coding - Python\hotels.xlsx")
hotels_table

Unnamed: 0      hotel  rooms  price
0             0    hotel_1     13    273
1             1    hotel_2     18     92
2             2    hotel_3     12    141
3             3    hotel_4     18    157
4             4    hotel_5      7    298
..          ...        ...    ...    ...
395         395  hotel_396      5    212
396         396  hotel_397     12     68
397         397  hotel_398     14    102
398         398  hotel_399     16    284
399         399  hotel_400     14    145

[400 rows x 4 columns]

In [4]:
preferences_table = pd.read_excel(r"C:\Users\lejda\Desktop\coding - Python\preferences.xlsx")
preferences_table

Unnamed: 0       guest      hotel  priority
0               0     guest_1  hotel_168         1
1               1     guest_1  hotel_207         2
2               2     guest_1  hotel_222         3
3               3     guest_1  hotel_124         4
4               4     guest_1  hotel_223         5
...           ...         ...        ...       ...
99528       99528  guest_4000  hotel_123        28
99529       99529  guest_4000  hotel_396        29
99530       99530  guest_4000  hotel_161        30
99531       99531  guest_4000  hotel_330        31
99532       99532  guest_4000  hotel_290        32

[99533 rows x 4 columns]

In [5]:
import numpy as np

In [8]:
guestt=np.array(guests_table)

In [9]:
guestt

array([[0, 'guest_1', 0.09],
       [1, 'guest_2', 0.0],
       [2, 'guest_3', 0.07],
       ...,
       [3997, 'guest_3998', 0.07],
       [3998, 'guest_3999', 0.08],
       [3999, 'guest_4000', 0.07]], dtype=object)

In [10]:
hotelt=np.array(hotels_table)
hotelt

array([[0, 'hotel_1', 13, 273],
       [1, 'hotel_2', 18, 92],
       [2, 'hotel_3', 12, 141],
       ...,
       [397, 'hotel_398', 14, 102],
       [398, 'hotel_399', 16, 284],
       [399, 'hotel_400', 14, 145]], dtype=object)

In [11]:
preferencest=np.array(preferences_table)
preferencest

array([[0, 'guest_1', 'hotel_168', 1],
       [1, 'guest_1', 'hotel_207', 2],
       [2, 'guest_1', 'hotel_222', 3],
       ...,
       [99530, 'guest_4000', 'hotel_161', 30],
       [99531, 'guest_4000', 'hotel_330', 31],
       [99532, 'guest_4000', 'hotel_290', 32]], dtype=object)

In [13]:
num_hotel=len(hotelt)

In [14]:
for guest in hotelt:
    while True: #while continues to work until it finds an hotel with rooms avaible
        hotel_random= np.random.randint(0, num_hotel)
        if hotelt[hotel_random]['rooms']>0:
            hotelt[hotel_random]['rooms'] -= 1 #it occupies a room
            break  

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices